// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/swagger-example/echo": {
            "post": {
                "description": "\u003c在展開的時候才會出現，此 api 詳細的描述\u003e\n\u003c在展開的時候才會出現，此 api 詳細的描述\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "\u003c這邊可以幫 api 新增標籤，做出分類的效果\u003e"
                ],
                "summary": "\u003c在不展開 api 的時候就可以看到的描述\u003e",
                "operationId": "echo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type bearer",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "word",
                        "name": "word",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.echoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HttpResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.HttpResp"
                        }
                    }
                }
            }
        },
        "/swagger-example/hello": {
            "get": {
                "description": "\u003c在展開的時候才會出現，此 api 詳細的描述\u003e\n\u003c在展開的時候才會出現，此 api 詳細的描述\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "\u003c這邊可以幫 api 新增標籤，做出分類的效果\u003e"
                ],
                "summary": "\u003c在不展開 api 的時候就可以看到的描述\u003e",
                "operationId": "hello",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type bearer",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "letter",
                        "name": "letter",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HttpResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.HttpResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.HttpResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "main.echoReq": {
            "type": "object",
            "required": [
                "word"
            ],
            "properties": {
                "word": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "<swagger 的 title>",
	Description:      "<就是描述>",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
